create table "public"."blogs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "title" text not null,
    "content" text not null
);


alter table "public"."blogs" enable row level security;

CREATE UNIQUE INDEX blogs_pkey ON public.blogs USING btree (id);

alter table "public"."blogs" add constraint "blogs_pkey" PRIMARY KEY using index "blogs_pkey";