import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SupabaseProvider from "./supabase-provider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={`h-full ${inter.className}`}>
        <div className="container mx-auto flex h-full max-w-5xl flex-col justify-between text-base">
          <Header />
          <SupabaseProvider>
            <div className="flex flex-col justify-center ">{children}</div>
          </SupabaseProvider>
          <Footer />
        </div>
      </body>
    </html>
  );
}
